In [1]:
# Pandas trabalha com dados tabulares e heterogêneos(diferentes tipos)
# Numpy trabalha com dados numéricos homogêneos em arrays
# IMPORTANTE o [] para procurar são diferentes em numpy e pandas, o [] em numpy é o index, e o [] no pandas é a coluna

In [1]:
import pandas as pd
import numpy as np

In [4]:
# Series: array unidimensional, array associado de rótulos (labels) de dados, chamado de índice
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj[0]

4

In [6]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [12]:
obj2['a']

-5

In [14]:
obj2['d'] = 6 # Alterando
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [16]:
obj2[['c', 'a', 'd']] # conjunto

c    3
a   -5
d    6
dtype: int64

In [19]:
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [17]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [18]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [22]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [23]:
'b' in obj2 # pergunta se tem o índice b no obj2

True

In [25]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 1600, 'Utah': 5000}
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 1600, 'Utah': 5000}

In [27]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon     1600
Utah       5000
dtype: int64

In [28]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
states

['California', 'Ohio', 'Oregon', 'Texas']

In [30]:
obj4 = pd.Series(sdata, index=states) # sobrescrever e adiciona e deixa em ordem
obj4

California        NaN
Ohio          35000.0
Oregon         1600.0
Texas         71000.0
dtype: float64

In [31]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [32]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [33]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [34]:
obj3

Ohio      35000
Texas     71000
Oregon     1600
Utah       5000
dtype: int64

In [37]:
obj4

California        NaN
Ohio          35000.0
Oregon         1600.0
Texas         71000.0
dtype: float64

In [39]:
obj3 + obj4 # Soma apenas os valores que tem, caso se não tiver o mesmo index no outro aparece um NaN

California         NaN
Ohio           70000.0
Oregon          3200.0
Texas         142000.0
Utah               NaN
dtype: float64

In [43]:
obj4.name = 'population'
obj4.index.name = 'state'

In [44]:
obj4

state
California        NaN
Ohio          35000.0
Oregon         1600.0
Texas         71000.0
Name: population, dtype: float64

In [45]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [46]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan'] # alterado no inplace

In [48]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [2]:
# DataFrame

In [15]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [14]:
data = {'nome': ['Kaique', 'Kawan'],
       'idade': [21, 22]}
pd.Series(data)

nome     [Kaique, Kawan]
idade           [21, 22]
dtype: object

In [16]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [18]:
pd.DataFrame(data, columns=['year', 'state', 'pop']) # data com os valores em uma lista, reescrevo em ordem com o columns

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [21]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [22]:
frame2['state'] # obtendo ele em uma Series

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [24]:
frame2.year # outro jeito de obter dados

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [28]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [29]:
frame2.loc['three', 'state'] # loc utilizando o index

'Ohio'

In [30]:
frame2['debt'] = 16.5

In [31]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [34]:
frame2['debt'] = [10, 20, 30 , 40 , 50, 60]

In [35]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5    10
two    2001    Ohio  1.7    20
three  2002    Ohio  3.6    30
four   2001  Nevada  2.4    40
five   2002  Nevada  2.9    50
six    2003  Nevada  3.2    60

In [36]:
frame2['debt'] = np.arange(6.)

In [37]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [38]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [40]:
frame2['debt'] = val # concatena os valores, porem as posições que não forem compativeis viram nan
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [43]:
frame2['eastern'] = frame2.state == 'Ohio'

In [44]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [45]:
del frame2['eastern']

In [46]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [47]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [48]:
pop = {'Nevada' : {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [49]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [51]:
frame3 = pd.DataFrame(pop, index=[2000, 2001, 2002])
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [52]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [53]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [58]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata, columns = ['Ohio', 'Nevada'])

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [64]:
frame3.index.name = 'year' # alterando os nomes
frame3.columns.name = 'state' # alterando os nomes
frame3.name = 'Dados'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [68]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [66]:
frame2.values # se tiverem dtypes distintos, sera escolhido de modo a acomodar todas as colunas

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [69]:
# Objetos Index

In [70]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj

a    0
b    1
c    2
dtype: int64

In [72]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [73]:
index[1:]

Index(['b', 'c'], dtype='object')

In [ ]:
index[1] = 'd' # TypeError objetos index são imutáveis

In [75]:
labels = pd.Index(np.arange(3)) # criando um index

In [76]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [78]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [79]:
obj2.index is labels

True

In [80]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [81]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [82]:
'Ohio' in frame3.columns

True

In [83]:
2003 in frame3.index

False

In [93]:
dados = pd.Series([1, 2, 3, 1, 2, 3], index=[1, 3, 4, 2, 6, 5])

In [95]:
dados # index errados

1    1
3    2
4    3
2    1
6    2
5    3
dtype: int64

In [96]:
list_correct = dados.index

In [97]:
dados = pd.Series([1, 2, 3, 1, 2, 3], index=sorted(list_correct)) # no index posso fazer direito ali, com dados.index

In [98]:
dados

1    1
2    2
3    3
4    1
5    2
6    3
dtype: int64

In [99]:
# Funcionaliadades essenciais
# Reindexação

In [100]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [101]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [106]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [108]:
obj3.reindex(range(6),method='ffill')
obj3

0      blue
2    purple
4    yellow
dtype: object

In [110]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [112]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [113]:
states = ['Texas', 'Utah', 'California']
states

['Texas', 'Utah', 'California']

In [115]:
frame.reindex(columns=states) # Funciona com colunas o reindex


Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [116]:
frame # não muda

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [120]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [130]:
states = ['Texas', 'Ohio', 'California']

In [131]:
frame2.loc[['a', 'b', 'c', 'd'], states]

Texas  Ohio  California
a    1.0   0.0         2.0
b    NaN   NaN         NaN
c    4.0   3.0         5.0
d    7.0   6.0         8.0

In [132]:
# Descartando entrades de um eixo

In [140]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [135]:
new_obj = obj.drop('c') # pega todos os valores menos o 'c'
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [141]:
obj.drop(['d', 'c'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [138]:
obj.drop(['d', 'c'], inplace=True)

In [139]:
obj

a    0.0
b    1.0
e    4.0
dtype: float64

In [142]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [143]:
data.drop(['Colorado', 'Ohio']) # drop pega sempre os index, por conta do axis=0 padrão

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [145]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [146]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [147]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [148]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [149]:
# Indexação, seleção e filtragem

In [150]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [151]:
obj['b']

1.0

In [152]:
obj[1] # jeito diferente de pegar o valor

1.0

In [153]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [154]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [155]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [156]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [157]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [158]:
obj['b':'c'] = 5 # modifica a seção
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [191]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one','two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [162]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [163]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [167]:
data[:2] # aparece os dois index

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [171]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [175]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [176]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [177]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [178]:
data[data < 5] = 0 # percorre cada um True coloca 0

In [179]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [190]:
# Seleção com loc e iloc

In [192]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [198]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [200]:
data.iloc[2, [3, 0, 1]] # Posições númericos

four    11
one      8
two      9
Name: Utah, dtype: int32

In [201]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [202]:
data.loc[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [207]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [205]:
data.three > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [206]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [209]:
# Índices inteiros

In [210]:
ser = pd.Series(np.arange(3.))

In [211]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [213]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [215]:
ser2[-1] # funcinou porquê não tem índices inteiros

2.0

In [217]:
ser[:1] 

0    0.0
dtype: float64

In [220]:
ser.loc[:1] # Para ser mais preciso quanto aos índices inteiros utiliza-se loc e iloc

0    0.0
1    1.0
dtype: float64

In [221]:
ser.iloc[:1]

0    0.0
dtype: float64

In [222]:
# Arimética e alinhamento de dados

In [223]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index =['a', 'c', 'e', 'f', 'g'])

In [224]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [225]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [226]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [231]:
df1 = pd.DataFrame(np.arange(9).reshape((3, 3)),
                 columns=list('bcd'),
                 index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12).reshape((4, 3)),
                 columns=list('bde'),
                 index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [232]:
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [233]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [234]:
df1 + df2 # coluna, linha com coluna, linha

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [237]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [238]:
df1

A
0  1
1  2

In [239]:
df2

B
0  3
1  4

In [241]:
df1 + df2 # se não tiverem em comum retorna NaN

A   B
0 NaN NaN
1 NaN NaN

In [242]:
# Métodos aritméticos com valores para preenchimento

In [243]:
df1 = pd.DataFrame(np.arange(12).reshape((3, 4)),
                  columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20).reshape((4, 5)),
                  columns=list('abcde'))

In [244]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [245]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [247]:
df2.loc[1, 'b'] = np.nan

In [248]:
df2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [249]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [251]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [252]:
df2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [254]:
df1.add(df2, fill_value=0) # adiciona e ignora o NaN caso não estiver em comum

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [255]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [256]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [257]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [259]:
df2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [260]:
df1.reindex(columns=df2.columns, fill_value=0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

In [261]:
# Operações entre DataFrame e Series

In [263]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [264]:
arr[0]

array([0., 1., 2., 3.])

In [266]:
arr - arr[0] # todos vão se subtraindo pelo arr[0] isso é chamado de broadcasting

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [268]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [269]:
series = frame.iloc[0]

In [270]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [272]:
frame - series # todos vão se subtraindo pelo series isso é chamado de broadcasting

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [273]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [275]:
frame + series2 # Se não estiverem em comum, retorna NaN

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [276]:
series3 = frame['d']

In [277]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [278]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [282]:
frame.sub(series3, axis='index') # todos foram subtraido (broadcasting)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [2]:
# Aplicação de funções e mapeamento

In [3]:
frame = pd.DataFrame(np.random.randn(4, 3),
                    columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    0.667794 -0.590901  1.693068
Ohio   -2.253511  0.086850 -0.399016
Texas   1.514962  0.014525 -1.681609
Oregon -0.461851  0.833079  0.135068

In [4]:
np.abs(frame)

b         d         e
Utah    0.667794  0.590901  1.693068
Ohio    2.253511  0.086850  0.399016
Texas   1.514962  0.014525  1.681609
Oregon  0.461851  0.833079  0.135068

In [6]:
np.mean(frame, axis=1)

Utah      0.589987
Ohio     -0.855226
Texas    -0.050707
Oregon    0.168765
dtype: float64

In [7]:
np.mean(frame, axis=0)

b   -0.133151
d    0.085888
e   -0.063122
dtype: float64

In [8]:
f = lambda x: x.max() - x.min()

In [17]:
frame.apply(f) # axis = 0, faz com coluna 

b    3.768473
d    1.423980
e    3.374677
dtype: float64

In [18]:
frame.apply(f, axis='columns')

Utah      2.283970
Ohio      2.340360
Texas     3.196571
Oregon    1.294930
dtype: float64

In [19]:
frame

b         d         e
Utah    0.667794 -0.590901  1.693068
Ohio   -2.253511  0.086850 -0.399016
Texas   1.514962  0.014525 -1.681609
Oregon -0.461851  0.833079  0.135068

In [20]:
frame['b'].max()

1.514962045447625

In [16]:
frame['b'].min()

-2.2535108345392625

In [21]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [22]:
frame.apply(f)

b         d         e
min -2.253511 -0.590901 -1.681609
max  1.514962  0.833079  1.693068

In [23]:
format = lambda x: '%.2f' % x

In [24]:
frame.applymap(format)

b      d      e
Utah     0.67  -0.59   1.69
Ohio    -2.25   0.09  -0.40
Texas    1.51   0.01  -1.68
Oregon  -0.46   0.83   0.14

In [26]:
frame['e'].map(format) # formatado

Utah       1.69
Ohio      -0.40
Texas     -1.68
Oregon     0.14
Name: e, dtype: object