In [1]:
# Pandas trabalha com dados tabulares e heterogêneos(diferentes tipos)
# Numpy trabalha com dados numéricos homogêneos em arrays
# IMPORTANTE o [] para procurar são diferentes em numpy e pandas, o [] em numpy é o index, e o [] no pandas é a coluna

In [1]:
import pandas as pd
import numpy as np

In [4]:
# Series: array unidimensional, array associado de rótulos (labels) de dados, chamado de índice
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj[0]

4

In [6]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [12]:
obj2['a']

-5

In [14]:
obj2['d'] = 6 # Alterando
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [16]:
obj2[['c', 'a', 'd']] # conjunto

c    3
a   -5
d    6
dtype: int64

In [19]:
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [17]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [18]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [22]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [23]:
'b' in obj2 # pergunta se tem o índice b no obj2

True

In [25]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 1600, 'Utah': 5000}
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 1600, 'Utah': 5000}

In [27]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon     1600
Utah       5000
dtype: int64

In [28]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
states

['California', 'Ohio', 'Oregon', 'Texas']

In [30]:
obj4 = pd.Series(sdata, index=states) # sobrescrever e adiciona e deixa em ordem
obj4

California        NaN
Ohio          35000.0
Oregon         1600.0
Texas         71000.0
dtype: float64

In [31]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [32]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [33]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [34]:
obj3

Ohio      35000
Texas     71000
Oregon     1600
Utah       5000
dtype: int64

In [37]:
obj4

California        NaN
Ohio          35000.0
Oregon         1600.0
Texas         71000.0
dtype: float64

In [39]:
obj3 + obj4 # Soma apenas os valores que tem, caso se não tiver o mesmo index no outro aparece um NaN

California         NaN
Ohio           70000.0
Oregon          3200.0
Texas         142000.0
Utah               NaN
dtype: float64

In [43]:
obj4.name = 'population'
obj4.index.name = 'state'

In [44]:
obj4

state
California        NaN
Ohio          35000.0
Oregon         1600.0
Texas         71000.0
Name: population, dtype: float64

In [45]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [46]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan'] # alterado no inplace

In [48]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [2]:
# DataFrame

In [15]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [14]:
data = {'nome': ['Kaique', 'Kawan'],
       'idade': [21, 22]}
pd.Series(data)

nome     [Kaique, Kawan]
idade           [21, 22]
dtype: object

In [16]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [18]:
pd.DataFrame(data, columns=['year', 'state', 'pop']) # data com os valores em uma lista, reescrevo em ordem com o columns

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [21]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [22]:
frame2['state'] # obtendo ele em uma Series

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [24]:
frame2.year # outro jeito de obter dados

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [28]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [29]:
frame2.loc['three', 'state'] # loc utilizando o index

'Ohio'

In [30]:
frame2['debt'] = 16.5

In [31]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [34]:
frame2['debt'] = [10, 20, 30 , 40 , 50, 60]

In [35]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5    10
two    2001    Ohio  1.7    20
three  2002    Ohio  3.6    30
four   2001  Nevada  2.4    40
five   2002  Nevada  2.9    50
six    2003  Nevada  3.2    60

In [36]:
frame2['debt'] = np.arange(6.)

In [37]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [38]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [40]:
frame2['debt'] = val # concatena os valores, porem as posições que não forem compativeis viram nan
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [43]:
frame2['eastern'] = frame2.state == 'Ohio'

In [44]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [45]:
del frame2['eastern']

In [46]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [47]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [48]:
pop = {'Nevada' : {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [49]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [51]:
frame3 = pd.DataFrame(pop, index=[2000, 2001, 2002])
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [52]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [53]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [58]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata, columns = ['Ohio', 'Nevada'])

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [64]:
frame3.index.name = 'year' # alterando os nomes
frame3.columns.name = 'state' # alterando os nomes
frame3.name = 'Dados'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [68]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [66]:
frame2.values # se tiverem dtypes distintos, sera escolhido de modo a acomodar todas as colunas

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [69]:
# Objetos Index

In [70]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj

a    0
b    1
c    2
dtype: int64

In [72]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [73]:
index[1:]

Index(['b', 'c'], dtype='object')

In [ ]:
index[1] = 'd' # TypeError objetos index são imutáveis

In [75]:
labels = pd.Index(np.arange(3)) # criando um index

In [76]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [78]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [79]:
obj2.index is labels

True

In [80]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [81]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [82]:
'Ohio' in frame3.columns

True

In [83]:
2003 in frame3.index

False

In [93]:
dados = pd.Series([1, 2, 3, 1, 2, 3], index=[1, 3, 4, 2, 6, 5])

In [95]:
dados # index errados

1    1
3    2
4    3
2    1
6    2
5    3
dtype: int64

In [96]:
list_correct = dados.index

In [97]:
dados = pd.Series([1, 2, 3, 1, 2, 3], index=sorted(list_correct)) # no index posso fazer direito ali, com dados.index

In [98]:
dados

1    1
2    2
3    3
4    1
5    2
6    3
dtype: int64